### ISSUE TITLE
Crashes reported by users

### ISSUE THREAD

**Issue by seshuvinay** [binaryfork/Spanny#5]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Rect android.graphics.drawable.Drawable.getBounds()' on a null object reference
       at android.text.style.DynamicDrawableSpan.getSize(DynamicDrawableSpan.java:78)
       at android.text.MeasuredText.addStyleRun(MeasuredText.java:206)
       at android.text.StaticLayout.generate(StaticLayout.java:285)
       at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
       at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
       at android.widget.TextView.makeSingleLayout(TextView.java:6415)
       at android.widget.TextView.makeNewLayout(TextView.java:6313)
       at android.widget.TextView.onMeasure(TextView.java:6670)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17561)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:875)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17561)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17561)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2618)
       at android.view.View.measure(View.java:17561)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2054)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1211)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1417)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1099)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5952)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:794)
       at android.view.Choreographer.doCallbacks(Choreographer.java:607)
       at android.view.Choreographer.doFrame(Choreographer.java:577)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:780)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5290)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```

I use Spanny to insert images in TextView. It works well. But I get this crash reported by users.

**Comment by aiKrice** [comment]
need some code. stack trace is not enough....
